{% set name = "wmctrl" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wmctrl-{{ version }}.tar.gz
  sha256: 66cbff72b0ca06a22ec3883ac3a4d7c41078bdae4fb7310f52951769b10e14e0
  patches:
    - fix-deprecated-command.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - wmctrl
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/antocuni/wmctrl
  summary: A tool to programmatically control windows inside X
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kynan
    - sodre
