{% set name = "wmctrl" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wmctrl-{{ version }}.tar.gz
  sha256: d806f65ac1554366b6e31d29d7be2e8893996c0acbb2824bbf2b1f49cf628a13
  patches:
    - fix-deprecated-command.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - wmctrl
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/antocuni/wmctrl
  summary: A tool to programmatically control windows inside X
  license: MIT
  # No license file in source distribution
  # See https://github.com/antocuni/wmctrl/issues/7
  # license_file: LICENSE

extra:
  recipe-maintainers:
    - kynan
    - sodre
