travis:
  secure:
    BINSTAR_TOKEN: KLEPzDvMEsXlzKemWiov+gCvnRh+U4VUwyNqNsQCbf2ZtcxEIDcqshbkTboBG9N5meYt2eco5ymFEJNaxZQQ8klsya0X8mNua/KAVlt8hA5OFcsKgBaUuPaMYJ7tWbFDUO29EODmFXP7S5QZPxHvKoVd3Ff0xtolV+2AJpfonLwl5fVdN2cTlGzdlhTUZTgwcBlRHH6Y8v8qDNrOS5MKiLovBjDCu4w0R2fLEkYvpR1xFgX56q07w2bv1gwYrKNd20MwpftunNj8bL9gXyIXBqHFnIkjCdXlMj3WYj7xkikj8pi2eCn4CjzjdpLuLv+mwGmLQL2ZSZy9KVSrrSwW3DDGp2pw3dyqPTDeG+HSwBoHLIUYqQxfgr4vEEih/GR1HlrXDVQOcS/CR2sUaOg0zMqYEy/xJIVunKFZ4/j19r784Rsx+g8vx7psmTb/TVvV8y56SI9uHS/kmxFBGRrudcetTAM6TVK+bYY/5QFpztPI+BkPo/yPizXvOOPIQvnAnV++dKSoBvN+VNAD8uZK7Kh0bsfS91bt9zyrzWiF84LoRw6GRB75m4ijKGnuj2mgKdKhphkpKK91CnxXdUTROQ9LYnd4aAivkupKg4zP/aho2FZ5bRbBT5HWfeudw3ic7zKC7c5F4UGQJn30HvvMQtdBfrDMPIhZzjueZui1vXs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
